#**Домашнее Задание 01**

##**1 Задание.** Создание одномерных массивов

In [100]:
import numpy as np
array_1_1 = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
array_1_2 = np.array([50, 100, 150, 200, 250, 300, 350, 400, 450, 500])
print(array_1_1)
print(array_1_2)

[ 100  200  300  400  500  600  700  800  900 1000]
[ 50 100 150 200 250 300 350 400 450 500]


##**2 Задание.** Двумерный массив, заполненный нулями

In [101]:
import numpy as np
array_2 = np.zeros((3, 3))
print(array_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##**3 Задание.** Двумерный массив, заполненный единицами

In [102]:
import numpy as np
array_3 = np.ones((3, 3))
print(array_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##**4 Задание.** Одномерный массив,(с помощью arange)

In [103]:
import numpy as np
array_4 = np.arange(1,25)
print(array_4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


##**5 Задание.** Форма данных для массива array_3

In [104]:
print("Форма массива:", array_3.shape)


Форма массива: (3, 3)


##**6 Задание.**Тип данных для массива array_3

In [105]:
print("Тип данных:", array_3.dtype)

Тип данных: float64


##**7 Задание.**Вывод первого и второго элемента массива array_4

In [106]:
first_element = array_4[0]
second_element = array_4[1]
print(first_element)
print(second_element)

1
2


##**8 Задание.** Нахождение 5-ого элемента массива array_4 (индексирование)

In [107]:
index_array = array_4[4]
print(index_array)

5


##**9 Задание.** Срез с первого по 21 (не включительно) элемент с шагом 3

In [126]:
slice_of_array = array_4[0:21:3]
print(slice_of_array)

[ 1  4  7 10 13 16 19]


##**10 Задание.** Поэлементное суммирование массивов

In [119]:
sum_of_array = array_1_1 + array_1_2
print(sum_of_array)

[ 150  300  450  600  750  900 1050 1200 1350 1500]


##**11 Задание.** Поэлементное умножение массивов

In [110]:
multiplication_of_array = array_1_1 * array_1_2
print(multiplication_of_array)

[  5000  20000  45000  80000 125000 180000 245000 320000 405000 500000]


##**12 Задание.** Нахождение среднего значения массива

In [111]:
mean_value = np.mean(array_1_1)
print(mean_value)

550.0


##**13 Задание.** Нахождение медианного значения массива

In [112]:
median_value = np.median(array_1_1)
np.median(array_1_1)
print(median_value)

550.0


##**14 Задание.** Перевод 90 градусов в радианы

In [113]:
import math
angle_in_radians = math.pi/2 
print(angle_in_radians)

1.5707963267948966


##**15 Задание.** Перевод из радиан в граддусы

In [114]:
angle_in_degrees = angle_in_radians * 180 / math.pi
print(angle_in_degrees)

90.0


##**16 Задание.** Перевод из градусов в радианы

In [115]:
angle_to_radians = angle_in_degrees * math.pi / 180 # из градусов в радианы
angle_to_radians 

1.5707963267948966