###**HOMEWORK 01**

##**1** Создание одномерного массива

In [62]:
import numpy as np
array_1_1 = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
array_1_2 = np.array([50, 100, 150, 200, 250, 300, 350, 400, 450, 500])
print(array_1_1)
print(array_1_2)

[ 100  200  300  400  500  600  700  800  900 1000]
[ 50 100 150 200 250 300 350 400 450 500]


##**2** Двумерный массив, заполненный нулями

In [63]:
import numpy as np
array_2 = np.zeros((3, 3))
print(array_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##**3** Двумерный массив, заполненный единицами

In [64]:
import numpy as np
array_3 = np.ones((3, 3))
print(array_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##**4** Одномерный массив,(с помощью arange)

In [65]:
import numpy as np
array_4 = np.arange(1,25)
print(array_4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


##**5** Форма данных для массива array_3

In [66]:
print("Форма массива:", array_3.shape)


Форма массива: (3, 3)


##**6**Тип данных для массива array_3

In [67]:
print("Тип данных:", array_3.dtype)

Тип данных: float64


##**7**Вывод первого и второго элемента массива array_4

In [68]:
first_element = array_4[0]
second_element = array_4[1]
print(first_element)
print(second_element)

1
2


##**8** Нахождение 5-ого элемента массива array_4 (индексирование)

In [69]:
index_array = array_4[4]
print(index_array)

5


##**9** Срез с первого по 23(включительно) элемент с шагом 3

In [70]:
slice_of_array = array_4[0:23:3]
print(slice_of_array)

[ 1  4  7 10 13 16 19 22]


##**10** Поэлементное суммирование массивов

In [71]:
sum_of_array = array_1_1 + array_1_2
print(sum_of_array)

[ 150  300  450  600  750  900 1050 1200 1350 1500]


##**11** Поэлементное умножение массивов

In [72]:
multiplication_of_array = array_1_1 * array_1_2
print(multiplication_of_array)

[  5000  20000  45000  80000 125000 180000 245000 320000 405000 500000]


##**12** Нахождение среднего значения массива

In [73]:
mean_value = np.mean(array_1_1)
print(mean_value)

550.0


##**13** Нахождение медианного значения массива

In [74]:
median_value = np.median(array_1_1)
np.median(array_1_1)
print(median_value)

550.0
